#!/bin/bash
SUBCOMMAND=$1
ARGUMENTS=${@:2}
ARGUMENTS_MISS2=${@:3}
case $SUBCOMMAND in 
  size)
    GetSize $ARGUMENTS
    ;;
  lead)
    if [ "$1" -eq "-d" ]; then
      lead $ARGUMENTS_MISS2
    else 
      TestLeader $ARGUMENTS
    fi
    ;;
  part)
    part $ARGUMENTS
    ;;
  print)
    PrintBlockchains $ARGUMENTS
    ;;
  gather)
    GatherLeaderResults $ARGUMENTS
    ;;
  test)
    ThroughputLatencyTester $ARGUMENTS
    ;;
  help)
    printf "\nLOGAN - A Blockchain Library built in OCaml\n\n\
SUBCOMMANDS\n\n\
lead          Run a Leader node\n\
part          Run a Participant node\n\
size          Print the size of the blockchain and/or mempools\n\
print         Print the contents of the blockchain and/or mempools\n\
test          Run a Logan test program\n\
gather        Gather test program results for analysis\n\n"
    ;;
esac